[package]
name = "stcjudge-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "stcjudge-gui"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
ctrlc.workspace = true
dirs.workspace = true
eframe.workspace = true
egui.workspace = true
egui_extras.workspace = true
flate2.workspace = true
image.workspace = true
notify-rust.workspace = true
reqwest.workspace = true
rfd.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
stcjudge = { path = "../core" }
tar.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
zip.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-app-kit.workspace = true
